#!/usr/bin/env python3
"""
engine/skill_adapter.py — Universal Skill Engine

Syncs skills from the canonical vault/Skills/ source to every connected
AI runtime in each runtime's native format.

Why this exists
───────────────
Every AI tool has its own skill / custom-instruction system:

  Claude Code   → ~/.claude/skills/*.md         (name + description frontmatter)
  Gemini CLI    → ~/.gemini/skills/*.md          (name + description frontmatter)
  Codex / GPT   → ~/.codex/skills/*.md           (name + description frontmatter)
  Custom AI      → {workspace}/skills/{slug}/SKILL.md  (flat SKILL.md per folder)

Without an adapter layer, you'd have to manually duplicate every skill across
every AI. One edit to a skill would require four updates. Skills would drift.

With this engine, vault/Skills/ is the single source of truth. Run:

    python -m engine sync-skills

…and every AI gets the same skills in its own native format. Add a skill once
to vault/Skills/ and it's everywhere.

Usage (CLI)
───────────
    python -m engine sync-skills                       # sync all runtimes
    python -m engine sync-skills --runtime claude      # one runtime only
    python -m engine sync-skills --runtime claude --runtime gemini
    python -m engine sync-skills --dry-run             # preview, no writes
    python -m engine sync-skills --list                # list discovered skills
    python -m engine sync-skills --reverse             # import FROM runtimes INTO vault

Extending
─────────
Add a new AI runtime by subclassing SkillAdapter and registering it in
ADAPTERS. You only need to implement:
  - name: str          — the --runtime key
  - target_root: Path  — where the AI looks for skills
  - write_skill()      — how to format and write one skill

Skill format (vault canonical)
───────────────────────────────
Each skill in vault/Skills/ is a Markdown file with optional YAML frontmatter:

    ---
    name: my-skill-name
    description: One-line description shown in skill lists
    type: skill           # optional, detected automatically
    targets: [claude, codex, gemini]  # optional, for filtering
    ---

    # My Skill Name

    Instructions the AI should follow when this skill is active...

If frontmatter is missing, the filename becomes the skill name.
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import sys
import textwrap
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional


# ── Defaults ──────────────────────────────────────────────────────────────────

_VAULT_ENV = os.environ.get("OMNI_VAULT_PATH", "")
_DEFAULT_VAULT = (
    Path(_VAULT_ENV).expanduser().resolve()
    if _VAULT_ENV
    else Path(__file__).parent.parent / "vault"
)

_SKILLS_SOURCE = _DEFAULT_VAULT / "Skills"

# Runtime target overrides via env (useful for non-standard installs)
_CLAUDE_SKILLS_ROOT = Path(
    os.environ.get("CC_CLAUDE_SKILLS_PATH", Path.home() / ".claude" / "skills")
).expanduser()

_GEMINI_SKILLS_ROOT = Path(
    os.environ.get("CC_GEMINI_SKILLS_PATH", Path.home() / ".gemini" / "skills")
).expanduser()

_CODEX_SKILLS_ROOT = Path(
    os.environ.get("CC_CODEX_SKILLS_PATH", Path.home() / ".codex" / "skills")
).expanduser()

_CUSTOM_AI_WORKSPACE = Path(
    os.environ.get("CC_CUSTOM_AI_WORKSPACE", Path.home() / ".custom-ai")
).expanduser()

# Skills that are engine meta-tools, not intended for AI runtimes as prompts.
# These live in vault/Skills/ but are MCP tool descriptions, not executable
# prompts — they document what a tool does, not what the AI should do.
_META_SKILLS = {
    "bootstrap-agent",
    "freshness-report",
    "list-skills",
    "list-vault",
    "read-skill",
    "read-vault-file",
    "record-handoff",
    "resolve-skills",
    "search-memory",
    "store-memory",
    "update-working-set",
    "verify-vault-file",
}

# Auto-generated header added to every synced skill file so AI tools can
# see where the skill came from and editors know not to edit the copy.
_AUTOGEN_COMMENT = (
    "<!-- AUTO-GENERATED by Command Center skill_adapter.py — "
    "edit the source in vault/Skills/ not here -->"
)


# ── Data model ────────────────────────────────────────────────────────────────

@dataclass
class Skill:
    """One canonical skill loaded from vault/Skills/."""
    slug: str                          # filesystem slug, e.g. "elite-landing-page"
    name: str                          # human name, e.g. "Elite Landing Page"
    description: str                   # one-line summary
    body: str                          # full markdown body (after frontmatter)
    raw: str                           # original file text including frontmatter
    source_path: Path                  # absolute path in vault
    targets: list[str] = field(default_factory=list)
    category: str = "knowledge"
    is_meta: bool = False              # True = MCP tool descriptor, skip for runtime sync


@dataclass
class SyncResult:
    """Result of syncing one skill to one runtime."""
    runtime: str
    skill_slug: str
    target_path: Path
    action: str   # "write", "skip", "unchanged", "dry_run"
    error: Optional[str] = None


# ── Frontmatter parser ────────────────────────────────────────────────────────

def _parse_frontmatter(text: str) -> tuple[dict[str, str], str]:
    """Split YAML frontmatter from body. Returns (metadata_dict, body_text)."""
    if not text.startswith("---"):
        return {}, text
    end = text.find("\n---", 3)
    if end == -1:
        return {}, text
    fm_block = text[3:end].strip()
    body = text[end + 4:].lstrip("\n")
    meta: dict[str, str] = {}
    for line in fm_block.splitlines():
        if ":" not in line:
            continue
        key, _, val = line.partition(":")
        meta[key.strip()] = val.strip().strip('"').strip("'")
    return meta, body


def _slugify(name: str) -> str:
    name = name.lower()
    name = re.sub(r"[^a-z0-9]+", "-", name)
    return name.strip("-")


# ── Skill loader ──────────────────────────────────────────────────────────────

def load_skills(source: Path = _SKILLS_SOURCE) -> list[Skill]:
    """Load all skills from vault/Skills/ (one level deep, *.md files)."""
    if not source.exists():
        return []

    skills: list[Skill] = []
    for path in sorted(source.glob("*.md")):
        try:
            raw = path.read_text(encoding="utf-8")
        except Exception:
            continue

        meta, body = _parse_frontmatter(raw)
        name = meta.get("name", path.stem.replace("-", " ").title())
        slug = _slugify(meta.get("name", path.stem))
        description = meta.get("description", "").strip()
        targets_raw = meta.get("targets", "")
        targets = [
            t.strip().lower().strip("[]")
            for t in re.split(r"[,\s]+", targets_raw)
            if t.strip().strip("[]")
        ]
        category = meta.get("category", "knowledge").strip() or "knowledge"
        is_meta = slug in _META_SKILLS

        skills.append(Skill(
            slug=slug,
            name=name,
            description=description,
            body=body,
            raw=raw,
            source_path=path,
            targets=targets,
            category=category,
            is_meta=is_meta,
        ))

    return skills


# ── Base adapter ──────────────────────────────────────────────────────────────

class SkillAdapter(ABC):
    """
    Base class for all AI runtime adapters.

    Each adapter knows:
      - WHERE the AI looks for skills (target_root)
      - HOW to format a skill for that AI (write_skill)

    The base class handles discovery, filtering, dry-run, and result tracking.
    Subclasses only need to implement the formatting logic.
    """

    #: Short key used with --runtime flag, e.g. "claude"
    name: str = ""

    #: Human-readable label for logs
    label: str = ""

    #: Where this AI looks for skill files
    target_root: Path = Path()

    def __init__(self) -> None:
        self._results: list[SyncResult] = []

    # ── Abstract interface ────────────────────────────────────────────────────

    @abstractmethod
    def format_skill(self, skill: Skill) -> tuple[Path, str]:
        """
        Transform one Skill into (target_path, file_content).

        target_path — absolute path where the file should be written
        file_content — the formatted text to write
        """
        ...

    # ── Default filter (overridable) ──────────────────────────────────────────

    def should_sync(self, skill: Skill) -> bool:
        """
        Return True if this skill should be synced to this runtime.

        Default: skip meta skills (MCP tool descriptors), sync everything else.
        If the skill has a `targets` list, only sync if this runtime is listed.
        """
        if skill.is_meta:
            return False
        if skill.targets and self.name not in skill.targets and "any-ai" not in skill.targets:
            return False
        return True

    # ── Sync engine ───────────────────────────────────────────────────────────

    def sync(
        self,
        skills: list[Skill],
        dry_run: bool = False,
        verbose: bool = True,
    ) -> list[SyncResult]:
        """Sync all applicable skills to this runtime's target directory."""
        self._results = []
        eligible = [s for s in skills if self.should_sync(s)]

        if not eligible:
            if verbose:
                print(f"  [{self.label}] no eligible skills to sync")
            return self._results

        if not dry_run:
            self.target_root.mkdir(parents=True, exist_ok=True)

        for skill in eligible:
            try:
                target_path, content = self.format_skill(skill)
            except Exception as exc:
                result = SyncResult(
                    runtime=self.name,
                    skill_slug=skill.slug,
                    target_path=self.target_root / f"{skill.slug}.md",
                    action="error",
                    error=str(exc),
                )
                self._results.append(result)
                if verbose:
                    print(f"  [{self.label}] ERROR {skill.slug}: {exc}")
                continue

            if dry_run:
                result = SyncResult(
                    runtime=self.name,
                    skill_slug=skill.slug,
                    target_path=target_path,
                    action="dry_run",
                )
                self._results.append(result)
                if verbose:
                    print(f"  [{self.label}] would write → {target_path}")
                continue

            # Only write if content changed (avoid touching mtimes needlessly)
            try:
                existing = target_path.read_text(encoding="utf-8") if target_path.exists() else None
            except Exception:
                existing = None

            if existing == content:
                result = SyncResult(
                    runtime=self.name,
                    skill_slug=skill.slug,
                    target_path=target_path,
                    action="unchanged",
                )
            else:
                target_path.parent.mkdir(parents=True, exist_ok=True)
                target_path.write_text(content, encoding="utf-8")
                result = SyncResult(
                    runtime=self.name,
                    skill_slug=skill.slug,
                    target_path=target_path,
                    action="write",
                )
                if verbose:
                    print(f"  [{self.label}] ✓ {skill.slug} → {target_path}")

            self._results.append(result)

        written = sum(1 for r in self._results if r.action == "write")
        skipped = sum(1 for r in self._results if r.action == "unchanged")
        if verbose and not dry_run:
            print(f"  [{self.label}] done — {written} written, {skipped} unchanged")

        return self._results

    # ── Reverse import ────────────────────────────────────────────────────────

    def import_to_vault(
        self,
        vault_skills_path: Path,
        dry_run: bool = False,
        verbose: bool = True,
    ) -> list[SyncResult]:
        """
        Import skills FROM this runtime's target directory INTO vault/Skills/.

        Use this when you've written skills directly in a runtime (e.g. you
        wrote a skill in ~/.claude/skills/) and want to promote it to the
        canonical vault so all runtimes get it.

        Only imports files that do NOT already exist in vault/Skills/ —
        this is a one-way promotion, not a merge. Existing vault skills win.
        """
        results: list[SyncResult] = []
        if not self.target_root.exists():
            if verbose:
                print(f"  [{self.label}] import: target root does not exist, skipping")
            return results

        for path in sorted(self.target_root.rglob("*.md")):
            try:
                content = path.read_text(encoding="utf-8")
            except Exception:
                continue
            if _AUTOGEN_COMMENT in content:
                continue  # skip files we wrote — they came from vault already

            meta, _ = _parse_frontmatter(content)
            name = meta.get("name", path.stem)
            slug = _slugify(name)
            vault_target = vault_skills_path / f"{slug}.md"

            if vault_target.exists():
                if verbose:
                    print(f"  [{self.label}] import skip (exists in vault): {slug}")
                continue

            if dry_run:
                results.append(SyncResult(
                    runtime=self.name,
                    skill_slug=slug,
                    target_path=vault_target,
                    action="dry_run",
                ))
                if verbose:
                    print(f"  [{self.label}] would import → vault: {slug}")
                continue

            vault_skills_path.mkdir(parents=True, exist_ok=True)
            vault_target.write_text(content, encoding="utf-8")
            results.append(SyncResult(
                runtime=self.name,
                skill_slug=slug,
                target_path=vault_target,
                action="write",
            ))
            if verbose:
                print(f"  [{self.label}] imported → vault: {vault_target}")

        return results


# ── Claude Code adapter ───────────────────────────────────────────────────────

class ClaudeAdapter(SkillAdapter):
    """
    Claude Code runtime adapter.

    Claude Code auto-loads skills from ~/.claude/skills/*.md.
    Each file needs a YAML frontmatter block with `name` and `description`.
    The body is the prompt / instructions Claude receives when the skill fires.

    Format:
        ---
        name: skill-name
        description: One-line description
        ---
        # Skill Name
        ...instructions...

    Claude Code matches skills by the `name` field and surfaces them via
    the /skill-name slash command or auto-trigger keywords.
    """

    name = "claude"
    label = "Claude Code"
    target_root = _CLAUDE_SKILLS_ROOT

    def format_skill(self, skill: Skill) -> tuple[Path, str]:
        target = self.target_root / f"{skill.slug}.md"
        frontmatter = f"---\nname: {skill.slug}\ndescription: {skill.description}\n---\n"
        content = f"{_AUTOGEN_COMMENT}\n{frontmatter}\n{skill.body.strip()}\n"
        return target, content


# ── Gemini CLI adapter ────────────────────────────────────────────────────────

class GeminiAdapter(SkillAdapter):
    """
    Gemini CLI runtime adapter.

    Gemini CLI loads context files from ~/.gemini/context/*.md (or a path
    configured in ~/.gemini/settings.json). Skills are formatted as plain
    Markdown with an optional name/description header comment so Gemini
    can surface them in its context panel.

    Override CC_GEMINI_SKILLS_PATH to point to a different directory if
    your Gemini CLI version uses a non-default path.
    """

    name = "gemini"
    label = "Gemini CLI"
    target_root = _GEMINI_SKILLS_ROOT

    def format_skill(self, skill: Skill) -> tuple[Path, str]:
        target = self.target_root / f"{skill.slug}.md"
        header = f"# {skill.name}\n\n> {skill.description}\n\n" if skill.description else f"# {skill.name}\n\n"
        content = f"{_AUTOGEN_COMMENT}\n{header}{skill.body.strip()}\n"
        return target, content


# ── Codex / GPT adapter ───────────────────────────────────────────────────────

class CodexAdapter(SkillAdapter):
    """
    Codex / OpenAI GPT adapter.

    Codex (and GPT-based tools like Cursor in GPT mode) can load skills from
    a configured skills directory. The format matches the Claude format —
    YAML frontmatter with name/description, Markdown body — because Codex
    also supports this convention via its context window injection.

    Override CC_CODEX_SKILLS_PATH to match where your Codex install looks.
    """

    name = "codex"
    label = "Codex / GPT"
    target_root = _CODEX_SKILLS_ROOT

    def format_skill(self, skill: Skill) -> tuple[Path, str]:
        target = self.target_root / f"{skill.slug}.md"
        frontmatter = f"---\nname: {skill.slug}\ndescription: {skill.description}\n---\n"
        content = f"{_AUTOGEN_COMMENT}\n{frontmatter}\n{skill.body.strip()}\n"
        return target, content


# ── Custom AI adapter ──────────────────────────────────────────────────────────

class Custom AIAdapter(SkillAdapter):
    """
    Custom AI gateway adapter.

    Custom AI loads skills from a workspace directory. Each skill lives in its
    own subfolder: {workspace}/skills/{slug}/SKILL.md

    This matches the convention used by agent workspaces that need skills to
    be self-contained — each skill folder can later include additional assets
    (examples, templates, supporting data) alongside the SKILL.md.

    Override CC_CUSTOM_AI_WORKSPACE to point to your Custom AI workspace root.
    """

    name = "custom-ai"
    label = "Custom AI"
    target_root = _CUSTOM_AI_WORKSPACE / "skills"

    def format_skill(self, skill: Skill) -> tuple[Path, str]:
        skill_dir = self.target_root / skill.slug
        target = skill_dir / "SKILL.md"
        header = f"# {skill.name}\n\n> {skill.description}\n\n" if skill.description else f"# {skill.name}\n\n"
        content = f"{_AUTOGEN_COMMENT}\n{header}{skill.body.strip()}\n"
        return target, content


# ── Registry ──────────────────────────────────────────────────────────────────

#: All registered adapters. Add new runtimes here.
ADAPTERS: dict[str, SkillAdapter] = {
    a.name: a
    for a in [
        ClaudeAdapter(),
        GeminiAdapter(),
        CodexAdapter(),
        Custom AIAdapter(),
    ]
}


# ── Public API ────────────────────────────────────────────────────────────────

def sync_skills(
    runtimes: Optional[list[str]] = None,
    source: Path = _SKILLS_SOURCE,
    dry_run: bool = False,
    verbose: bool = True,
) -> dict[str, list[SyncResult]]:
    """
    Sync vault skills to one or more AI runtimes.

    Args:
        runtimes:  List of runtime names to sync (default: all registered runtimes).
        source:    Path to vault/Skills/ (default: auto-detected from vault).
        dry_run:   If True, print what would happen without writing anything.
        verbose:   Print progress to stdout.

    Returns:
        dict mapping runtime name → list of SyncResult objects.
    """
    skills = load_skills(source)
    if not skills:
        if verbose:
            print(f"No skills found in {source}")
        return {}

    target_adapters = (
        {k: v for k, v in ADAPTERS.items() if k in runtimes}
        if runtimes
        else ADAPTERS
    )

    if verbose:
        mode = "[DRY RUN] " if dry_run else ""
        print(f"{mode}Syncing {len(skills)} skills to {len(target_adapters)} runtime(s)...")

    results: dict[str, list[SyncResult]] = {}
    for runtime_name, adapter in target_adapters.items():
        if verbose:
            print(f"\n  Adapter: {adapter.label} → {adapter.target_root}")
        results[runtime_name] = adapter.sync(skills, dry_run=dry_run, verbose=verbose)

    return results


def import_from_runtimes(
    runtimes: Optional[list[str]] = None,
    vault_skills_path: Path = _SKILLS_SOURCE,
    dry_run: bool = False,
    verbose: bool = True,
) -> dict[str, list[SyncResult]]:
    """
    Import skills FROM runtime directories INTO vault/Skills/.

    Only promotes skills that don't already exist in the vault.
    Vault always wins on conflicts — this is a one-way promotion.
    """
    target_adapters = (
        {k: v for k, v in ADAPTERS.items() if k in runtimes}
        if runtimes
        else ADAPTERS
    )

    results: dict[str, list[SyncResult]] = {}
    for runtime_name, adapter in target_adapters.items():
        results[runtime_name] = adapter.import_to_vault(
            vault_skills_path, dry_run=dry_run, verbose=verbose
        )
    return results


def list_skills_table(source: Path = _SKILLS_SOURCE) -> None:
    """Print a formatted table of all discovered vault skills."""
    skills = load_skills(source)
    if not skills:
        print(f"No skills found in {source}")
        return

    print(f"\n{'SLUG':<40} {'CATEGORY':<14} {'META':<6} DESCRIPTION")
    print("─" * 100)
    for s in sorted(skills, key=lambda x: (x.category, x.slug)):
        meta_flag = "yes" if s.is_meta else ""
        desc = s.description[:55] + "…" if len(s.description) > 55 else s.description
        print(f"{s.slug:<40} {s.category:<14} {meta_flag:<6} {desc}")
    print(f"\nTotal: {len(skills)} skills ({sum(1 for s in skills if s.is_meta)} meta)")


# ── CLI ───────────────────────────────────────────────────────────────────────

def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="python -m engine sync-skills",
        description=textwrap.dedent("""\
            Universal Skill Engine — sync vault/Skills/ to every AI runtime.

            Vault is the canonical source. Run this after adding or editing a skill
            to push it to Claude Code, Gemini CLI, Codex, and Custom AI simultaneously.
        """),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument(
        "--runtime", "-r",
        action="append",
        dest="runtimes",
        metavar="NAME",
        choices=list(ADAPTERS.keys()),
        help=f"Runtime to sync (choices: {', '.join(ADAPTERS)}). Repeat for multiple. Default: all.",
    )
    p.add_argument(
        "--dry-run", "-n",
        action="store_true",
        help="Preview what would be written without making any changes.",
    )
    p.add_argument(
        "--list", "-l",
        action="store_true",
        help="List all discovered vault skills and exit.",
    )
    p.add_argument(
        "--reverse",
        action="store_true",
        help="Import skills FROM runtimes INTO vault/Skills/ (promote, no overwrite).",
    )
    p.add_argument(
        "--source",
        type=Path,
        default=_SKILLS_SOURCE,
        metavar="PATH",
        help=f"Path to vault/Skills/ directory (default: {_SKILLS_SOURCE})",
    )
    p.add_argument(
        "--quiet", "-q",
        action="store_true",
        help="Suppress progress output.",
    )
    return p


def main(argv: Optional[list[str]] = None) -> int:
    parser = _build_parser()
    args = parser.parse_args(argv)

    verbose = not args.quiet

    if args.list:
        list_skills_table(args.source)
        return 0

    if args.reverse:
        import_from_runtimes(
            runtimes=args.runtimes,
            vault_skills_path=args.source,
            dry_run=args.dry_run,
            verbose=verbose,
        )
        return 0

    results = sync_skills(
        runtimes=args.runtimes,
        source=args.source,
        dry_run=args.dry_run,
        verbose=verbose,
    )

    errors = [
        r for runtime_results in results.values()
        for r in runtime_results
        if r.action == "error"
    ]
    if errors:
        print(f"\n{len(errors)} error(s) during sync:", file=sys.stderr)
        for e in errors:
            print(f"  [{e.runtime}] {e.skill_slug}: {e.error}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
